version: "3.5"

services:

    database:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        networks:
            - app-net
        

    backend:
        build: ./backend
        ports:
            - 8000:8000
        env_file:
            - ./.env-back
        depends_on:
            - database
        networks:
            - app-virtual-network
        
    frontend:
        build: ./frontend
        ports:
           - 3000:3000
        env_file:
            - ./.env-front
        networks:
            - app-net

volumes:
    postgres_data:

networks:
    app-net: