apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-west-2

nodeGroups:
  - name: webapp1
    instanceType: t2.micro
    desiredCapacity: 10
    volumeSize: 80