on: push


jobs:
  push-and-deploy:
    name: Push the images to Dockerhub and deploy the on eks
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2


      - name: Login to Dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v2
        with:
          context: ../../backend
          repository: aelyss/backend
          tag_with_ref: true
          tag_with_sha: true
          tags: latest, ${{ github.sha }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v2
        with:
          context: ../../frontend
          repository: aelyss/frontend
          tag_with_ref: true
          tag_with_sha: true
          tags: latest, ${{ github.sha }}

      - name: Deploy the images.
        uses: cancue/eks-action@v0.0.2
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          cluster_name: cluster1
        with:
          args: |
            kubectl set image deployment backend -n default backend=aelyss/backend:latest
            kubectl set image deployment frontend -n default frontend=aelyss/frontend:latest
            kubectl rollout status deployment/backend -n default
            kubectl rollout status deployment/frontend -n default